application: bel-adm
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
# Home Directory
- url: /h
  static_dir: h
# Portal Directory
- url: /p
  static_dir: p
#- url: /p/.*
#  script: account.py
#  login: required
#  auth_fail_action: unauthorized
- url: /admin
  script: main.application
- url: /login
  script: main.application
- url: /.*
  script: main.application

libraries:
- name: markupsafe                                                              
  version: latest 

builtins:
- remote_api: on
