application: beladmin
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /.*
  script: main.application

libraries:
- name: markupsafe                                                              
  version: latest 

builtins:
- remote_api: on
