application: bel-adm
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js

# Admin page
- url: /admin[USP]
  script: main.application
  
- url: /admin
  script: main.application
  
- url: /au1[cve]
  script: wrkbk.application
#
- url: /portal
  script: main.application
  
- url: /workbook
  script: wrkbk.application
#
- url: /tutor
  script: main.application
  
- url: /logout
  script: main.application
  
- url: /signin
  script: main.application
  
- url: /test
  script: wrkbk.application
  
- url: /.*
  script: main.application

libraries:
- name: markupsafe                                                              
  version: latest
- name: jinja2
  version: latest

builtins:
- remote_api: on
