application: bel-adm
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js

# Admin pages
- url: /admin[USP]
  script: main2.application
  
- url: /admin
  script: main2.application
  secure: always
  
- url: /au1[cve]
  script: main2.application
  
# Main Pages
- url: /portal
  script: main2.application
  secure: always
  
- url: /workbook
  script: main2.application
#
- url: /tutor
  script: main.application
  
- url: /logout
  script: main2.application
  
- url: /signin
  script: main2.application
  
- url: /signup
  script: main2.application
  secure: always

- url: /login
  script: main2.application
  secure: always

- url: /forgot
  script: main2.application
  secure: always
  
- url: /.*
  script: main2.application

libraries:
- name: markupsafe                                                              
  version: latest
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.1"

builtins:
- remote_api: on
