application: bel-adm
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: img/favicon\.ico

# Admin pages
- url: /admin[USP]
  script: main2.application
  
- url: /admin
  script: main2.application
  secure: always
  
- url: /au[cve]
  script: main2.application
  secure: always
  
- url: /modify
  script: main2.application
  secure: always
  
- url: /loader
  script: main2.application
  secure: always
  
- url: /upload
  script: main2.application
  secure: always
  
- url: /serve
  script: main2.application
  secure: always
  
# Main Pages
- url: /portal
  script: main2.application
  secure: always
  
- url: /workbook
  script: main2.application

# Student Pages

- url: /su[cve]
  script: main2.application
  secure: always
  
- url: /chk
  script: main2.application
  secure: always
  
- url: /tutor
  script: main.application
  
- url: /logout
  script: main2.application
  
- url: /signin
  script: main2.application
  
- url: /signup
  script: main2.application
  secure: always

- url: /login
  script: main2.application
  secure: always

- url: /forgot
  script: main2.application
  secure: always

- url: /cloud
  script: main2.application

- url: /loader
  script: main2.application

- url: /.*
  script: main2.application

libraries:
- name: markupsafe                                                              
  version: latest
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.1"

builtins:
- remote_api: on
